version: '3.8'

networks:
  monitor-net:
    driver: bridge


services:
    alertmanager-sms:
        image: python:latest
        container_name: alertmanager-sms
        build: .
        restart: unless-stopped
        ports:
          - "5000:5000"
        networks:
            - monitor-net
        labels:
             org.label-schema.group: "monitoring"