version: '3.8'
networks:
  monitor-net:
    driver: bridge

services:
  ###############################################################
  #                     Nginx                                  #
  ###############################################################
    nginx:
        image: nginx:latest
        container_name: nginx
        volumes:
            - "./nginx/nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro"
            - "./nginx/nginx-conf/gitlab-http.conf:/etc/nginx/conf.d/gitlab-http.conf:ro"
            - "./nginx/nginx-logs:/var/log/nginx"
            - "./nginx/nginx-conf/ssl:/etc/letsencrypt"
        ports:
            - '80:80'
            - '443:443'

        restart: unless-stopped
#        depends_on:
#            - gitlab_app
#        links:
#            - gitlab_app
        networks:
            - monitor-net

  ###############################################################
  #                     GitLab                                  #
  ###############################################################
    gitlab_app:
        image: gitlab/gitlab-ce:latest
        container_name: gitlab
        hostname: 'git.zion.com'
        environment:
            GITLAB_OMNIBUS_CONFIG: |
                external_url 'https://gitlab.zion.com'

            DB_ADAPTER: postgresql
            DB_HOST: 192.168.1.122
            DB_PORT: 5432
            DB_USER: gitlab
            DB_PASS: Pass2014
            DB_NAME: gitlabhq_production
            DB_EXTENSION: pg_trgm
#
            REDIS_HOST: 192.168.1.122
            REDIS_PORT: 6379

            GITLAB_ROOT_PASSWORD: Pass2014
            GITLAB_ROOT_EMAIL: test@test.com

            GITLAB_EMAIL: notifications@zion.com
            GITLAB_EMAIL_REPLY_TO: noreply@zion.com
            GITLAB_INCOMING_EMAIL_ADDRESS: reply@zion.com

        expose:
            - "443"
        volumes:
            - './gitlab/config:/etc/gitlab'
            - './gitlab/logs:/var/log/gitlab'
            - './gitlab/data:/var/opt/gitlab'
        restart: unless-stopped
#        ports:
#            - '80:80'
#            - '443:443'
        networks:
            - monitor-net
        labels:
             org.label-schema.group: "gitlab"
        depends_on:
            - redis
            - postgresql
            - nginx
        links:
            - postgresql
            - redis
            - nginx

  ###############################################################
  #                     GitLab runner                           #
  ###############################################################
    runner:
      image: gitlab/gitlab-runner:latest
      restart: unless-stopped
      container_name: gitlab_runner
      environment:
            - CI_SERVER_URL=https://gitlab.zion.com
      volumes:
            - '/opt/runner:/etc/gitlab-runner'
      networks:
            - monitor-net

  ###############################################################
  #                     PostgreSQL                              #
  ###############################################################
    postgresql:
      image: postgres:11-buster
      container_name: postgresql-11-buster
      environment:
        POSTGRES_USER: gitlab
        POSTGRES_PASSWORD: Pass2014
        PGDATA: /var/lib/postgresql/data/pgdata
        DB_NAME: gitlabhq_production
        DB_EXTENSION: pg_trgm,btree_gist
      restart: unless-stopped
      ports:
            - '5432:5432'
      volumes:
            - ./postgres/postgres-data:/var/lib/postgresql/data
      networks:
        - monitor-net

  ###############################################################
  #                     redis                                   #
  ###############################################################
    redis:
      image: redis:latest
      restart: always
      container_name: gitlab_redis
      command:
        - --loglevel warning
#      volumes:
#        - ./volumes/redis:/var/lib/redis
      restart: unless-stopped
      networks:
        - monitor-net

  ###############################################################
  #                     postfix                                   #
  ###############################################################
    redis:
      image: postfixadmin
      restart: always
      container_name: postfix
      restart: unless-stopped
      environment:
          POSTFIXADMIN_DB_TYPE: postgresql
          POSTFIXADMIN_DB_HOST: postgresql
          POSTFIXADMIN_DB_USER: postgres
          POSTFIXADMIN_DB_NAME: postfixadmin
          POSTFIXADMIN_DB_PASSWORD: postgres
      ports:
        - 8089:80
      networks:
        - monitor-net