{
 "title": "IPMI-Blade-server-66",
 "description": "Charts from ipmitool in node exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "HOST:",
    "query": "label_values(node_ipmi_status, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Temperatures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ipmi_temperature_celsius{instance='192.168.25.66'}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "ipmi_dcmi_power_consumption_watts{instance='192.168.25.66'}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ipmi_temperature_celsius{instance='192.168.25.66'}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Power",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ipmi_dcmi_power_consumption_watts{instance='192.168.25.66'}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Fans",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "rotrpm" }
   ],
   "targets": [
    {
     "expr": "ipmi_fan_speed_rpm{instance='192.168.25.66'}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Voltages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "ipmi_voltage_volts{instance='192.168.25.66'}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ipmi_sensor_state{instance='192.168.25.66'}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Power cost 30d",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyCZK" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ipmi_dcmi_power_consumption_watts{instance='192.168.25.66'} * 30 * 24 * 0.0062"
    }
   ]
  },
  {
   "title": "Power usage 30d",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ipmi_dcmi_power_consumption_watts{instance='192.168.25.66'} * 30 * 24 "
    }
   ]
  }
 ]
}