{
 "title": "SNMP / Ubiquiti / WiFi",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "devices",
    "label": "Devices",
    "query": {
     "query": "label_values(up{job=~\"snmp.*\"}, instance)"
    }
   },
   {
    "name": "device_interfaces",
    "label": "Interface",
    "query": {
     "query": "query_result(ifOperStatus{job=~\"snmp.*\",instance=~\"$devices\"}==1)"
    }
   },
   {
    "name": "device_model",
    "query": {
     "query": "label_values(unifiApSystemModel{job=~\"snmp.*\",instance=~\"$devices\"}, unifiApSystemModel)"
    }
   },
   {
    "name": "device_firmware_version",
    "query": {
     "query": "label_values(unifiApSystemVersion{job=~\"snmp.*\",instance=~\"$devices\"}, unifiApSystemVersion)"
    }
   },
   {
    "name": "device_mac_addresses",
    "query": {
     "query": "label_values(ifPhysAddress{job=~\"snmp.*\",instance=~\"$devices\"}, ifPhysAddress)"
    }
   },
   {
    "name": "device_main_ip",
    "query": {
     "query": "label_values(unifiApSystemIp{job=~\"snmp.*\",instance=~\"$devices\"}, unifiApSystemIp)"
    }
   },
   {
    "name": "device_ESSIDs",
    "label": "Interface",
    "query": {
     "query": "label_values(unifiVapEssId{job=~\"snmp.*\",instance=~\"$devices\"}, unifiVapEssId)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traffic on the air",
   "type": "graph",
   "description": "This is the global overview of all wireless traffic coming from and going to the access points.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(unifiVapRxBytes{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))*8",
     "legendFormat": "In"
    },
    {
     "expr": "sum(irate(unifiVapTxBytes{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Packets on the air",
   "type": "graph",
   "description": "This is the global overview of all wireless traffic coming from and going to the access points.\n\nIf this graph spikes up relative to the traffic numbers, you might see degraded overall throughput.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(unifiVapRxPackets{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "In"
    },
    {
     "expr": "sum(irate(unifiVapRxDropped{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "In, dropped"
    },
    {
     "expr": "sum(irate(unifiVapRxErrors{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "In, errors"
    },
    {
     "expr": "sum(irate(unifiVapTxPackets{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "Out"
    },
    {
     "expr": "sum(irate(unifiVapTxDropped{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "Out, dropped"
    },
    {
     "expr": "sum(irate(unifiVapTxErrors{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "Out, errors"
    }
   ]
  },
  {
   "title": "Traffic on the wire",
   "type": "graph",
   "description": "This is the global overview of all traffic coming from and going to the access points through the wired network.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ifHCInOctets{instance=~\"$devices\",ifName=~\"eth.*\"}[5m]))*8",
     "legendFormat": "In"
    },
    {
     "expr": "sum(irate(ifHCOutOctets{instance=~\"$devices\",ifName=~\"eth.*\"}[5m]))*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Packets on the wire",
   "type": "graph",
   "description": "This is the global overview of all packets coming from and going to the access points through the wired network.\n\nIf this graph spikes up relative to the traffic numbers, you might see degraded overall throughput.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(unifiIfRxPackets{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "In"
    },
    {
     "expr": "sum(irate(unifiIfRxMulticast{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "In, multicast"
    },
    {
     "expr": "sum(irate(unifiIfRxDropped{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "In, dropped"
    },
    {
     "expr": "sum(irate(unifiIfRxError{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "In, error"
    },
    {
     "expr": "sum(irate(unifiIfTxPackets{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "Out"
    },
    {
     "expr": "sum(irate(unifiIfTxMulticast{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "Out, multicast"
    },
    {
     "expr": "sum(irate(unifiIfTxDropped{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "Out, dropped"
    },
    {
     "expr": "sum(irate(unifiIfTxError{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "Out, error"
    }
   ]
  },
  {
   "title": "Models",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 32 },
   "options": {
    "content": "Models: $device_model  \nFirmware versions: $device_firmware_version  \n"
   },
   "targets": [
    { "expr": "{{$device_model}}" }
   ]
  },
  {
   "title": "$devices ESSIDs",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 32 },
   "options": { "content": "$device_ESSIDs" },
   "targets": [
    { "expr": "{{$device_model}}" }
   ]
  },
  {
   "title": "Worst 3 response times by devices",
   "type": "graph",
   "description": "If any device is consistently above the others, this might indicate a problem. Consider rebooting that device, upgrading it, or putting another one nearby to reduce load.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(3,scrape_duration_seconds{job=~\"snmp.*\",instance=~\"$devices\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Device: $devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 }, "repeat": "devices" },
  {
   "title": "Traffic on air - $devices",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(unifiVapRxBytes{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))*8",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "sum(irate(unifiVapTxBytes{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))*8",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  },
  {
   "title": "Packets on the air - $devices",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(unifiVapRxPackets{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "In"
    },
    {
     "expr": "sum(irate(unifiVapRxDropped{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "In, dropped"
    },
    {
     "expr": "sum(irate(unifiVapRxErrors{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "In, errors"
    },
    {
     "expr": "sum(irate(unifiVapTxPackets{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "Out"
    },
    {
     "expr": "sum(irate(unifiVapTxDropped{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "Out, dropped"
    },
    {
     "expr": "sum(irate(unifiVapTxErrors{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "Out, errors"
    }
   ]
  },
  { "title": "Device: $devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Traffic on air - $devices",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(unifiVapRxBytes{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))*8",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "sum(irate(unifiVapTxBytes{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))*8",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  },
  {
   "title": "Packets on the air - $devices",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(unifiVapRxPackets{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "In"
    },
    {
     "expr": "sum(irate(unifiVapRxDropped{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "In, dropped"
    },
    {
     "expr": "sum(irate(unifiVapRxErrors{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "In, errors"
    },
    {
     "expr": "sum(irate(unifiVapTxPackets{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "Out"
    },
    {
     "expr": "sum(irate(unifiVapTxDropped{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "Out, dropped"
    },
    {
     "expr": "sum(irate(unifiVapTxErrors{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "Out, errors"
    }
   ]
  },
  { "title": "Device: $devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Traffic on air - $devices",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(unifiVapRxBytes{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))*8",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "sum(irate(unifiVapTxBytes{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))*8",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  },
  {
   "title": "Packets on the air - $devices",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(unifiVapRxPackets{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "In"
    },
    {
     "expr": "sum(irate(unifiVapRxDropped{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "In, dropped"
    },
    {
     "expr": "sum(irate(unifiVapRxErrors{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "In, errors"
    },
    {
     "expr": "sum(irate(unifiVapTxPackets{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "Out"
    },
    {
     "expr": "sum(irate(unifiVapTxDropped{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "Out, dropped"
    },
    {
     "expr": "sum(irate(unifiVapTxErrors{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "Out, errors"
    }
   ]
  },
  { "title": "Device: $devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Traffic on air - $devices",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(unifiVapRxBytes{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))*8",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "sum(irate(unifiVapTxBytes{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))*8",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  },
  {
   "title": "Packets on the air - $devices",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(unifiVapRxPackets{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "In"
    },
    {
     "expr": "sum(irate(unifiVapRxDropped{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "In, dropped"
    },
    {
     "expr": "sum(irate(unifiVapRxErrors{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "In, errors"
    },
    {
     "expr": "sum(irate(unifiVapTxPackets{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "Out"
    },
    {
     "expr": "sum(irate(unifiVapTxDropped{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "Out, dropped"
    },
    {
     "expr": "sum(irate(unifiVapTxErrors{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "Out, errors"
    }
   ]
  },
  { "title": "Device: $devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Traffic on air - $devices",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(unifiVapRxBytes{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))*8",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "sum(irate(unifiVapTxBytes{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))*8",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  },
  {
   "title": "Packets on the air - $devices",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(unifiVapRxPackets{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "In"
    },
    {
     "expr": "sum(irate(unifiVapRxDropped{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "In, dropped"
    },
    {
     "expr": "sum(irate(unifiVapRxErrors{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "In, errors"
    },
    {
     "expr": "sum(irate(unifiVapTxPackets{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "Out"
    },
    {
     "expr": "sum(irate(unifiVapTxDropped{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "Out, dropped"
    },
    {
     "expr": "sum(irate(unifiVapTxErrors{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "Out, errors"
    }
   ]
  },
  { "title": "Device: $devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Traffic on air - $devices",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(unifiVapRxBytes{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))*8",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "sum(irate(unifiVapTxBytes{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))*8",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  },
  {
   "title": "Packets on the air - $devices",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(unifiVapRxPackets{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "In"
    },
    {
     "expr": "sum(irate(unifiVapRxDropped{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "In, dropped"
    },
    {
     "expr": "sum(irate(unifiVapRxErrors{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "In, errors"
    },
    {
     "expr": "sum(irate(unifiVapTxPackets{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "Out"
    },
    {
     "expr": "sum(irate(unifiVapTxDropped{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "Out, dropped"
    },
    {
     "expr": "sum(irate(unifiVapTxErrors{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "Out, errors"
    }
   ]
  },
  { "title": "Device: $devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Traffic on air - $devices",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(unifiVapRxBytes{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))*8",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "sum(irate(unifiVapTxBytes{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))*8",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  },
  {
   "title": "Packets on the air - $devices",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(unifiVapRxPackets{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "In"
    },
    {
     "expr": "sum(irate(unifiVapRxDropped{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "In, dropped"
    },
    {
     "expr": "sum(irate(unifiVapRxErrors{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "In, errors"
    },
    {
     "expr": "sum(irate(unifiVapTxPackets{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "Out"
    },
    {
     "expr": "sum(irate(unifiVapTxDropped{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "Out, dropped"
    },
    {
     "expr": "sum(irate(unifiVapTxErrors{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "Out, errors"
    }
   ]
  },
  { "title": "Device: $devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Traffic on air - $devices",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(unifiVapRxBytes{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))*8",
     "legendFormat": "In {{ifName}}"
    },
    {
     "expr": "sum(irate(unifiVapTxBytes{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))*8",
     "legendFormat": "Out {{ifName}}"
    }
   ]
  },
  {
   "title": "Packets on the air - $devices",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(unifiVapRxPackets{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "In"
    },
    {
     "expr": "sum(irate(unifiVapRxDropped{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "In, dropped"
    },
    {
     "expr": "sum(irate(unifiVapRxErrors{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "In, errors"
    },
    {
     "expr": "sum(irate(unifiVapTxPackets{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "Out"
    },
    {
     "expr": "sum(irate(unifiVapTxDropped{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "Out, dropped"
    },
    {
     "expr": "sum(irate(unifiVapTxErrors{job=~\"snmp.*\",instance=~\"$devices\"}[5m]))",
     "legendFormat": "Out, errors"
    }
   ]
  }
 ]
}