version: '3'

services:
    postgres-12:
        image: postgres:12.7-buster
        container_name: postgres-12
        environment:
            POSTGRES_USER: $POSTGRES_USERNAME
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - ${PWD}/postgres-data/12:/var/lib/postgresql/data
        ports:
            - ${POSTG_PORT_12}:5432
        restart: unless-stopped

    postgres-9.6:
        image: postgres:9.3
        container_name: postgres-9.3
        environment:
            POSTGRES_USER: $POSTGRES_USERNAME
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - ${PWD}/postgres-data/9.6:/var/lib/postgresql/data
        ports:
            - ${POSTG_PORT_9}:5432
        restart: unless-stopped

    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_USERNAME
            PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
            PGDATA: /var/lib/pgadmin
#          PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
#          PGADMIN_CONFIG_LOGIN_BANNER: "Authorised users only!"
            PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
        volumes:
            - ${PWD}/pgadmin-data:/var/lib/pgadmin/
        ports:
            - ${PGADMIN_PORT}:80
        restart: always

    nodeexporter:
        image: prom/node-exporter:latest
        container_name: nodeexporter
        volumes:
            - /nodeexporter/proc:/host/proc:ro
            - /nodeexporter/sys:/host/sys:ro
            - /nodeexporter:/rootfs:ro
        command:
            - '--path.procfs=/host/proc'
            - '--path.rootfs=/rootfs'
            - '--path.sysfs=/host/sys'
            - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
        restart: unless-stopped
        network_mode: host
        expose:
            - 9100

    cadvisor:
        image: gcr.io/google-containers/cadvisor:latest
        container_name: cadvisor
        volumes:
            - /cadvisor:/rootfs:ro
            - /cadvisor/var/run:/var/run:rw
            - /cadvisor/sys:/sys:ro
            - /cadvisor/var/lib/bladesystem/:/var/lib/bladesystem:ro
            - /cadvisor/cgroup:/cgroup:ro
        restart: unless-stopped
        network_mode: host