global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'instance_down'] #группировать правила
  group_wait: 20s         #  время_ожидания_перед_отправкой_уведомления_для_группы
  group_interval: 5m      #  время_отправки_повторного_сообщения_для_группы
  repeat_interval: 3h     #  время_до_отправки_повторного_сообщения

  receiver: 'alerta'

  routes:

      - match:
          alertname: smswebhook
        receiver: 'webhook'
        continue: true

      - match:
        receiver: 'email'
        continue: true

      - match:
        receiver: 'alerta'

receivers:
  - name: 'email'
    email_configs:
      - to: ''             # адрес_электронной_почты_получателя
        send_resolved: true
        from: ''               # адрес_электронной_почты_отправителя
        smarthost: smtp.mail.ru:587
        auth_username: ''              # имя_пользователя
        auth_identity: ''              # имя_пользователя
        auth_password: ''
        require_tls: true

  - name: "alerta"
    webhook_configs:
      - url: 'http://{IP}:9080/api/webhooks/prometheus'
        send_resolved: true
        http_config:
          basic_auth:
            username: admin@alerta.io
            password: ecopass

  - name: 'webhook'
    webhook_configs:
      - url: 'http://{IP}:5050/send'
        send_resolved: true


templates:
  - ./template/template.tmpl