proxy:
  image: leanlabs/nginx:latest
  container_name: nginx
  volumes:
    - "./build/conf.d:/etc/nginx/conf.d"
    - "./build/certs:/etc/nginx/certs"
    - "./build/sites-enabled:/etc/nginx/sites-enabled"
  links:
    - kanban:kanban
  ports:
    - "4443:443"
    - "8096:80"

kanban:
  image: leanlabs/kanban:1.7.2
  container_name: kanban
  environment:
    # URL on which Leanlabs Kanban will be reachable
    - KANBAN_SERVER_HOSTNAME=http://10.210.10.20:8096
    # This string is used to generate user auth tokens
    - KANBAN_SECURITY_SECRET=qwerty
    # Your GitLab host URL
    - KANBAN_GITLAB_URL=https://10.210.10.20
    # Your GitLab OAuth client ID
    - KANBAN_GITLAB_CLIENT=e9874d3b253fc68e1eece4816d4dbd3262b8e356d1c984c3a524788455883156
    # Your GitLab OAuth client secret key
    - KANBAN_GITLAB_SECRET=ce6cbd0eacedb10399c113fdc54915c94a3b28ff15d1901b1c3ac55f81e62ad9
    # Wheter to enable sign up with user API token
    - KANBAN_ENABLE_SIGNUP=true
    # Redis server address - IP:PORT
    - KANBAN_REDIS_ADDR=redis:6379
  links:
    - redis:redis
  command: ./kanban server

redis:
  image: leanlabs/redis:latest
  container_name: redis

